### ISSUE TITLE
dota2.get_players, dota2.get_patches & dota2webapi no longer working

### ISSUE THREAD

**Issue by HugoTLR** [c00kie17/liquipediapy#17]
I wanted to rerun all tests from current project state to be sure my  future PR hasn't break anything.

(HEAD detached at 3710936) ==> Last commit of this repo

# get_players()

dota_obj = dota("appname")
players = dota_obj.get_players()

```
F:\Projets\liquipediapy (HEAD detached at 3710936)
(venv) λ python examples\dota_test.py
Traceback (most recent call last):
  File "examples\dota_test.py", line 5, in <module>
    players = dota_obj.get_players()
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\liquipediapy\dota.py", line 31, in get_players
    key = index_values[i]
IndexError: list index out of range
```

----
# get_patches()

dota_obj = dota("appname")
patches = dota_obj.get_patches() 

```
F:\Projets\liquipediapy (HEAD detached at 3710936)
(venv) λ python examples\dota_test.py
Traceback (most recent call last):
  File "examples\dota_test.py", line 19, in <module>
    patches = dota_obj.get_patches()
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\liquipediapy\dota.py", line 203, in get_patches
    key = index_values[i]
IndexError: list index out of range
```

---
# dota2webapi

liquipediapy_object_dota = liquipediapy('appname','dota2')
match_details = liquipediapy_object_dota.dota2webapi('4225454337')

```
F:\Projets\liquipediapy (HEAD detached at 3710936)
(venv) λ python examples\liquid_test.py
Traceback (most recent call last):
  File "examples\liquid_test.py", line 7, in <module>
    match_details = liquipediapy_object_dota.dota2webapi('4225454337')
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\liquipediapy\liquipediapy.py", line 40, in dota2webapi
    if res['dota2webapi']['isresult'] >= 1:
KeyError: 'dota2webapi'
```

**Comment by c00kie17** [comment]
I need check whats wrong and fix these dont think they are related to your MR
