### ISSUE TITLE
get_team_info() no longer works for counterstrike/dota teams.

### ISSUE THREAD

**Issue by Kushtrim-88** [c00kie17/liquipediapy#7]
The default usage of the method :

team_details = counterstrike_obj.get_team_info('Team Liquid',True)

throws out this error:

Traceback (most recent call last):
  File "teams.py", line 5, in <module>
    team_details = counterstrike_obj.get_team_info('Team Liquid',True)
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python38-32\lib\site-packages\liquipediapy\counterstrike.py", line 104, in get_team_info
    team['team_roster'] = team_object.get_team_roster(soup)
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python38-32\lib\site-packages\liquipediapy\counterstrike_modules\team.py", line 65, in get_team_roster
    team_roster = roster_cards[0]
IndexError: list index out of range

Same thing seems to happen with DOTA 2 teams, 

Error: 

Traceback (most recent call last):
  File "teams.py", line 5, in <module>
    team_details = dota_obj.get_team_info('Hippomaniacs',True)
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python38-32\lib\site-packages\liquipediapy\dota.py", line 91, in get_team_info
    team['results'] = team_object.get_team_achivements(soup)
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python38-32\lib\site-packages\liquipediapy\dota_modules\team.py", line 108, in get_team_achivements
    indexes = rows[0]
IndexError: list index out of range

**Comment by est0n14n** [comment]
This fixed in [#12](https://github.com/c00kie17/liquipediapy/pull/12#issue-597541412)
